# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Admin_form.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(700, 531)
        MainWindow.setMaximumSize(QtCore.QSize(700, 531))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tableWidget = QtGui.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem4, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuAction = QtGui.QMenu(self.menubar)
        self.menuAction.setObjectName(_fromUtf8("menuAction"))
        self.menuUser_Management = QtGui.QMenu(self.menubar)
        self.menuUser_Management.setObjectName(_fromUtf8("menuUser_Management"))
        self.menuUser_Management_2 = QtGui.QMenu(self.menuUser_Management)
        self.menuUser_Management_2.setObjectName(_fromUtf8("menuUser_Management_2"))
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionForgot_password = QtGui.QAction(MainWindow)
        self.actionForgot_password.setObjectName(_fromUtf8("actionForgot_password"))
        self.actionDelete_User = QtGui.QAction(MainWindow)
        self.actionDelete_User.setObjectName(_fromUtf8("actionDelete_User"))
        self.actionProfile = QtGui.QAction(MainWindow)
        self.actionProfile.setObjectName(_fromUtf8("actionProfile"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionExit_2 = QtGui.QAction(MainWindow)
        self.actionExit_2.setObjectName(_fromUtf8("actionExit_2"))
        self.actionMy_Profile = QtGui.QAction(MainWindow)
        self.actionMy_Profile.setObjectName(_fromUtf8("actionMy_Profile"))
        self.actionUser_Profile = QtGui.QAction(MainWindow)
        self.actionUser_Profile.setObjectName(_fromUtf8("actionUser_Profile"))
        self.actionDelete_USer = QtGui.QAction(MainWindow)
        self.actionDelete_USer.setObjectName(_fromUtf8("actionDelete_USer"))
        self.actionEdit_User_Profile = QtGui.QAction(MainWindow)
        self.actionEdit_User_Profile.setObjectName(_fromUtf8("actionEdit_User_Profile"))
        self.actionAdd_New_User = QtGui.QAction(MainWindow)
        self.actionAdd_New_User.setObjectName(_fromUtf8("actionAdd_New_User"))
        self.actionDelete_User_2 = QtGui.QAction(MainWindow)
        self.actionDelete_User_2.setObjectName(_fromUtf8("actionDelete_User_2"))
        self.menuAction.addAction(self.actionForgot_password)
        self.menuAction.addAction(self.actionProfile)
        self.menuAction.addSeparator()
        self.menuAction.addAction(self.actionExit_2)
        self.menuUser_Management_2.addAction(self.actionEdit_User_Profile)
        self.menuUser_Management_2.addAction(self.actionAdd_New_User)
        self.menuUser_Management_2.addSeparator()
        self.menuUser_Management_2.addAction(self.actionDelete_User_2)
        self.menuUser_Management.addAction(self.actionMy_Profile)
        self.menuUser_Management.addAction(self.actionUser_Profile)
        self.menuUser_Management.addAction(self.menuUser_Management_2.menuAction())
        self.menubar.addAction(self.menuAction.menuAction())
        self.menubar.addAction(self.menuUser_Management.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Admin", None))
        self.label.setText(_translate("MainWindow", "Welcome", None))
        self.label_2.setText(_translate("MainWindow", "Admin", None))
        self.pushButton_2.setText(_translate("MainWindow", "Logout", None))
        self.menuAction.setTitle(_translate("MainWindow", "Action", None))
        self.menuUser_Management.setTitle(_translate("MainWindow", "View", None))
        self.menuUser_Management_2.setTitle(_translate("MainWindow", "User Management", None))
        self.actionForgot_password.setText(_translate("MainWindow", "Forgot Password", None))
        self.actionDelete_User.setText(_translate("MainWindow", "Delete User", None))
        self.actionProfile.setText(_translate("MainWindow", "Profile", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionExit_2.setText(_translate("MainWindow", "Exit", None))
        self.actionMy_Profile.setText(_translate("MainWindow", "My Profile", None))
        self.actionUser_Profile.setText(_translate("MainWindow", "User Profile", None))
        self.actionDelete_USer.setText(_translate("MainWindow", "Delete User", None))
        self.actionEdit_User_Profile.setText(_translate("MainWindow", "Edit User Profile", None))
        self.actionAdd_New_User.setText(_translate("MainWindow", "Add New User", None))
        self.actionDelete_User_2.setText(_translate("MainWindow", "Delete User", None))

