# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Admin_form.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(700, 531)
        MainWindow.setMaximumSize(QtCore.QSize(700, 531))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 4, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_2.addWidget(self.pushButton)
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.tableWidget = QtGui.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuAction = QtGui.QMenu(self.menubar)
        self.menuAction.setObjectName(_fromUtf8("menuAction"))
        self.menuProfile = QtGui.QMenu(self.menuAction)
        self.menuProfile.setObjectName(_fromUtf8("menuProfile"))
        self.menuUser_profile = QtGui.QMenu(self.menuProfile)
        self.menuUser_profile.setObjectName(_fromUtf8("menuUser_profile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionForgot_password = QtGui.QAction(MainWindow)
        self.actionForgot_password.setObjectName(_fromUtf8("actionForgot_password"))
        self.actionDelete_User = QtGui.QAction(MainWindow)
        self.actionDelete_User.setObjectName(_fromUtf8("actionDelete_User"))
        self.actionMy_Profile = QtGui.QAction(MainWindow)
        self.actionMy_Profile.setObjectName(_fromUtf8("actionMy_Profile"))
        self.actionUser_Profile = QtGui.QAction(MainWindow)
        self.actionUser_Profile.setObjectName(_fromUtf8("actionUser_Profile"))
        self.actionDelete_USer = QtGui.QAction(MainWindow)
        self.actionDelete_USer.setObjectName(_fromUtf8("actionDelete_USer"))
        self.actionEdit_User_Profile = QtGui.QAction(MainWindow)
        self.actionEdit_User_Profile.setObjectName(_fromUtf8("actionEdit_User_Profile"))
        self.actionAdd_New_User = QtGui.QAction(MainWindow)
        self.actionAdd_New_User.setObjectName(_fromUtf8("actionAdd_New_User"))
        self.actionDelete_User_2 = QtGui.QAction(MainWindow)
        self.actionDelete_User_2.setObjectName(_fromUtf8("actionDelete_User_2"))
        self.actionEdit_my_profile = QtGui.QAction(MainWindow)
        self.actionEdit_my_profile.setObjectName(_fromUtf8("actionEdit_my_profile"))
        self.actionUser_profile_management = QtGui.QAction(MainWindow)
        self.actionUser_profile_management.setObjectName(_fromUtf8("actionUser_profile_management"))
        self.actionDelete_user = QtGui.QAction(MainWindow)
        self.actionDelete_user.setObjectName(_fromUtf8("actionDelete_user"))
        self.actionEdit_user_profile = QtGui.QAction(MainWindow)
        self.actionEdit_user_profile.setObjectName(_fromUtf8("actionEdit_user_profile"))
        self.actionAdd_new_user = QtGui.QAction(MainWindow)
        self.actionAdd_new_user.setObjectName(_fromUtf8("actionAdd_new_user"))
        self.actionShow_user_list = QtGui.QAction(MainWindow)
        self.actionShow_user_list.setObjectName(_fromUtf8("actionShow_user_list"))
        self.actionExit_3 = QtGui.QAction(MainWindow)
        self.actionExit_3.setObjectName(_fromUtf8("actionExit_3"))
        self.menuUser_profile.addAction(self.actionEdit_user_profile)
        self.menuUser_profile.addSeparator()
        self.menuUser_profile.addAction(self.actionAdd_new_user)
        self.menuProfile.addAction(self.actionEdit_my_profile)
        self.menuProfile.addSeparator()
        self.menuProfile.addAction(self.menuUser_profile.menuAction())
        self.menuAction.addAction(self.menuProfile.menuAction())
        self.menuAction.addSeparator()
        self.menuAction.addAction(self.actionExit_3)
        self.menubar.addAction(self.menuAction.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Admin", None))
        self.pushButton.setText(_translate("MainWindow", "Delete User", None))
        self.pushButton_2.setText(_translate("MainWindow", "Logout", None))
        self.label.setText(_translate("MainWindow", "Welcome", None))
        self.label_2.setText(_translate("MainWindow", "Admin", None))
        self.menuAction.setTitle(_translate("MainWindow", "Action", None))
        self.menuProfile.setTitle(_translate("MainWindow", "Profile management", None))
        self.menuUser_profile.setTitle(_translate("MainWindow", "User management", None))
        self.actionForgot_password.setText(_translate("MainWindow", "Forgot Password", None))
        self.actionDelete_User.setText(_translate("MainWindow", "Delete User", None))
        self.actionMy_Profile.setText(_translate("MainWindow", "My Profile", None))
        self.actionUser_Profile.setText(_translate("MainWindow", "User Profile", None))
        self.actionDelete_USer.setText(_translate("MainWindow", "Delete User", None))
        self.actionEdit_User_Profile.setText(_translate("MainWindow", "Edit User Profile", None))
        self.actionAdd_New_User.setText(_translate("MainWindow", "Add New User", None))
        self.actionDelete_User_2.setText(_translate("MainWindow", "Delete User", None))
        self.actionEdit_my_profile.setText(_translate("MainWindow", "Edit my profile", None))
        self.actionUser_profile_management.setText(_translate("MainWindow", "User profile management", None))
        self.actionDelete_user.setText(_translate("MainWindow", "Delete user profile", None))
        self.actionEdit_user_profile.setText(_translate("MainWindow", "Edit user profile", None))
        self.actionAdd_new_user.setText(_translate("MainWindow", "Add new user", None))
        self.actionShow_user_list.setText(_translate("MainWindow", "Show user list", None))
        self.actionExit_3.setText(_translate("MainWindow", "Exit", None))

